<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    //custom query
    public function getListCategories() {

        $query = $this->getEntityManager()->createQuery(
            'SELECT p,c 
                   FROM AppBundle:Product p
                   JOIN p.category c
                '
        );

        return $query->getResult();
    }

    // with query bulder-same as above with sql:

//    /**
//     * @param Connection $connection
//     * @param string $name
//     * @return mixed[]
//     * @throws DBALException
//     */
//    public function test(Connection $connection, string $name)
//    {
//      $qb = $connection->createQueryBuilder();
//      $qb
//          ->select('name')
//          ->from('products')
//          ->where('name = :name')
//          ->setParameter('name', $name);
//
//    }
}
